name = "MVS+Core"
author = "MVS+"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4521805af0c223e41d6f6540bfd2f6bc527144d8bd27cf9bdd2a6b5ea352321"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
